# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.28)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS VTK::vtkbuild VTK::loguru VTK::kwiml VTK::vtksys VTK::utf8 VTK::CommonCore VTK::CommonCore-private-kit-links VTK::kissfft VTK::CommonMath VTK::CommonTransforms VTK::exprtk VTK::CommonMisc VTK::CommonSystem VTK::CommonSystem-private-kit-links VTK::pugixml VTK::CommonDataModel VTK::CommonExecutionModel VTK::ImagingCore VTK::ImagingMath VTK::FiltersCore VTK::CommonColor VTK::CommonComputationalGeometry VTK::fmt VTK::FiltersGeneral VTK::FiltersGeometry VTK::FiltersSources VTK::RenderingCore VTK::opengl VTK::RenderingUI VTK::glew VTK::RenderingOpenGL2 VTK::RenderingOpenGL2-private-kit-links VTK::RenderingVolume VTK::RenderingVolumeOpenGL2 VTK::RenderingImage VTK::eigen VTK::FiltersStatistics VTK::doubleconversion VTK::lz4 VTK::lzma VTK::zlib VTK::IOCore VTK::IOLegacy VTK::ParallelCore VTK::diy2 VTK::expat VTK::IOXMLParser VTK::IOXML VTK::ParallelDIY VTK::FiltersExtraction VTK::InteractionStyle VTK::ImagingSources VTK::ImagingGeneral)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target VTK::vtkbuild
add_library(VTK::vtkbuild INTERFACE IMPORTED)

# Create imported target VTK::loguru
add_library(VTK::loguru STATIC IMPORTED)

set_target_properties(VTK::loguru PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:dl>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::kwiml
add_library(VTK::kwiml INTERFACE IMPORTED)

set_target_properties(VTK::kwiml PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::vtksys
add_library(VTK::vtksys STATIC IMPORTED)

set_target_properties(VTK::vtksys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "dl"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::utf8
add_library(VTK::utf8 INTERFACE IMPORTED)

set_target_properties(VTK::utf8 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::CommonCore
add_library(VTK::CommonCore STATIC IMPORTED)

set_target_properties(VTK::CommonCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::kwiml;VTK::vtksys;\$<LINK_ONLY:VTK::utf8>;\$<LINK_ONLY:VTK::loguru>;Threads::Threads;\$<LINK_ONLY:\$<\$<PLATFORM_ID:SunOS>:socket>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:SunOS>:nsl>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:Android>:log>>"
)

# Create imported target VTK::CommonCore-private-kit-links
add_library(VTK::CommonCore-private-kit-links INTERFACE IMPORTED)

set_target_properties(VTK::CommonCore-private-kit-links PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:\$<\$<PLATFORM_ID:SunOS>:socket>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:SunOS>:nsl>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:Android>:log>>"
)

# Create imported target VTK::kissfft
add_library(VTK::kissfft STATIC IMPORTED)

set_target_properties(VTK::kissfft PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "kiss_fft_scalar=double"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::CommonMath
add_library(VTK::CommonMath STATIC IMPORTED)

set_target_properties(VTK::CommonMath PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::kissfft"
)

# Create imported target VTK::CommonTransforms
add_library(VTK::CommonTransforms STATIC IMPORTED)

set_target_properties(VTK::CommonTransforms PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonMath;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::exprtk
add_library(VTK::exprtk INTERFACE IMPORTED)

set_target_properties(VTK::exprtk PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::CommonMisc
add_library(VTK::CommonMisc STATIC IMPORTED)

set_target_properties(VTK::CommonMisc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonMath;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:VTK::exprtk>"
)

# Create imported target VTK::CommonSystem
add_library(VTK::CommonSystem STATIC IMPORTED)

set_target_properties(VTK::CommonSystem PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:WIN32>:wsock32>>;\$<LINK_ONLY:Threads::Threads>"
)

# Create imported target VTK::CommonSystem-private-kit-links
add_library(VTK::CommonSystem-private-kit-links INTERFACE IMPORTED)

set_target_properties(VTK::CommonSystem-private-kit-links PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:\$<\$<PLATFORM_ID:WIN32>:wsock32>>;\$<LINK_ONLY:Threads::Threads>"
)

# Create imported target VTK::pugixml
add_library(VTK::pugixml STATIC IMPORTED)

set_target_properties(VTK::pugixml PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::CommonDataModel
add_library(VTK::CommonDataModel STATIC IMPORTED)

set_target_properties(VTK::CommonDataModel PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonMath;VTK::CommonTransforms;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::pugixml>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::CommonExecutionModel
add_library(VTK::CommonExecutionModel STATIC IMPORTED)

set_target_properties(VTK::CommonExecutionModel PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>"
)

# Create imported target VTK::ImagingCore
add_library(VTK::ImagingCore STATIC IMPORTED)

set_target_properties(VTK::ImagingCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonTransforms>"
)

# Create imported target VTK::ImagingMath
add_library(VTK::ImagingMath STATIC IMPORTED)

set_target_properties(VTK::ImagingMath PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonDataModel>"
)

# Create imported target VTK::FiltersCore
add_library(VTK::FiltersCore STATIC IMPORTED)

set_target_properties(VTK::FiltersCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMisc;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::CommonColor
add_library(VTK::CommonColor STATIC IMPORTED)

set_target_properties(VTK::CommonColor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel"
)

# Create imported target VTK::CommonComputationalGeometry
add_library(VTK::CommonComputationalGeometry STATIC IMPORTED)

set_target_properties(VTK::CommonComputationalGeometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel"
)

# Create imported target VTK::fmt
add_library(VTK::fmt STATIC IMPORTED)

set_target_properties(VTK::fmt PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_variadic_templates"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::FiltersGeneral
add_library(VTK::FiltersGeneral STATIC IMPORTED)

set_target_properties(VTK::FiltersGeneral PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMisc;VTK::FiltersCore;\$<LINK_ONLY:VTK::CommonComputationalGeometry>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::fmt>"
)

# Create imported target VTK::FiltersGeometry
add_library(VTK::FiltersGeometry STATIC IMPORTED)

set_target_properties(VTK::FiltersGeometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::FiltersSources
add_library(VTK::FiltersSources STATIC IMPORTED)

set_target_properties(VTK::FiltersSources PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonDataModel;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonComputationalGeometry>;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersGeneral>"
)

# Create imported target VTK::RenderingCore
add_library(VTK::RenderingCore STATIC IMPORTED)

set_target_properties(VTK::RenderingCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMath;VTK::FiltersCore;\$<LINK_ONLY:VTK::CommonColor>;\$<LINK_ONLY:VTK::CommonComputationalGeometry>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::FiltersGeometry>;\$<LINK_ONLY:VTK::FiltersSources>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::opengl
add_library(VTK::opengl INTERFACE IMPORTED)

set_target_properties(VTK::opengl PROPERTIES
  INTERFACE_LINK_LIBRARIES "OpenGL::GLES3;OpenGL::EGL"
)

# Create imported target VTK::RenderingUI
add_library(VTK::RenderingUI STATIC IMPORTED)

set_target_properties(VTK::RenderingUI PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::RenderingCore;\$<LINK_ONLY:android>"
)

# Create imported target VTK::glew
add_library(VTK::glew STATIC IMPORTED)

set_target_properties(VTK::glew PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GLEW_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::opengl"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::RenderingOpenGL2
add_library(VTK::RenderingOpenGL2 STATIC IMPORTED)

set_target_properties(VTK::RenderingOpenGL2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::FiltersGeneral;VTK::RenderingCore;VTK::RenderingUI;VTK::glew;\$<LINK_ONLY:VTK::CommonExecutionModel>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::opengl>;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:android>"
)

# Create imported target VTK::RenderingOpenGL2-private-kit-links
add_library(VTK::RenderingOpenGL2-private-kit-links INTERFACE IMPORTED)

set_target_properties(VTK::RenderingOpenGL2-private-kit-links PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:android>"
)

# Create imported target VTK::RenderingVolume
add_library(VTK::RenderingVolume STATIC IMPORTED)

set_target_properties(VTK::RenderingVolume PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonExecutionModel;VTK::RenderingCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::ImagingCore>"
)

# Create imported target VTK::RenderingVolumeOpenGL2
add_library(VTK::RenderingVolumeOpenGL2 STATIC IMPORTED)

set_target_properties(VTK::RenderingVolumeOpenGL2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::ImagingCore;VTK::ImagingMath;VTK::RenderingCore;VTK::RenderingOpenGL2;VTK::RenderingVolume;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::FiltersSources>;\$<LINK_ONLY:VTK::glew>;\$<LINK_ONLY:VTK::opengl>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::RenderingImage
add_library(VTK::RenderingImage STATIC IMPORTED)

set_target_properties(VTK::RenderingImage PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonExecutionModel;VTK::RenderingCore;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::ImagingCore>"
)

# Create imported target VTK::eigen
add_library(VTK::eigen INTERFACE IMPORTED)

set_target_properties(VTK::eigen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::FiltersStatistics
add_library(VTK::FiltersStatistics STATIC IMPORTED)

set_target_properties(VTK::FiltersStatistics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::eigen>;\$<LINK_ONLY:VTK::FiltersGeneral>"
)

# Create imported target VTK::doubleconversion
add_library(VTK::doubleconversion STATIC IMPORTED)

set_target_properties(VTK::doubleconversion PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::lz4
add_library(VTK::lz4 STATIC IMPORTED)

set_target_properties(VTK::lz4 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::lzma
add_library(VTK::lzma STATIC IMPORTED)

set_target_properties(VTK::lzma PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::zlib
add_library(VTK::zlib STATIC IMPORTED)

set_target_properties(VTK::zlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::IOCore
add_library(VTK::IOCore STATIC IMPORTED)

set_target_properties(VTK::IOCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::doubleconversion>;\$<LINK_ONLY:VTK::lz4>;\$<LINK_ONLY:VTK::lzma>;\$<LINK_ONLY:VTK::utf8>;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:VTK::zlib>"
)

# Create imported target VTK::IOLegacy
add_library(VTK::IOLegacy STATIC IMPORTED)

set_target_properties(VTK::IOLegacy PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::IOCore;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::ParallelCore
add_library(VTK::ParallelCore STATIC IMPORTED)

set_target_properties(VTK::ParallelCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::IOLegacy>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::diy2
add_library(VTK::diy2 INTERFACE IMPORTED)

set_target_properties(VTK::diy2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::expat
add_library(VTK::expat STATIC IMPORTED)

set_target_properties(VTK::expat PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1;${_IMPORT_PREFIX}/include/vtk-9.1/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.1/"
)

# Create imported target VTK::IOXMLParser
add_library(VTK::IOXMLParser STATIC IMPORTED)

set_target_properties(VTK::IOXMLParser PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;\$<LINK_ONLY:VTK::IOCore>;\$<LINK_ONLY:VTK::expat>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::IOXML
add_library(VTK::IOXML STATIC IMPORTED)

set_target_properties(VTK::IOXML PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonExecutionModel;VTK::IOXMLParser;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::IOCore>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::ParallelDIY
add_library(VTK::ParallelDIY STATIC IMPORTED)

set_target_properties(VTK::ParallelDIY PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "DIY_NO_THREADS"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonSystem;VTK::ParallelCore;VTK::diy2;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::FiltersGeometry>;\$<LINK_ONLY:VTK::IOXML>"
)

# Create imported target VTK::FiltersExtraction
add_library(VTK::FiltersExtraction STATIC IMPORTED)

set_target_properties(VTK::FiltersExtraction PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonCore;VTK::CommonExecutionModel;VTK::FiltersGeneral;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersStatistics>;\$<LINK_ONLY:VTK::ParallelDIY>"
)

# Create imported target VTK::InteractionStyle
add_library(VTK::InteractionStyle STATIC IMPORTED)

set_target_properties(VTK::InteractionStyle PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonDataModel;VTK::RenderingCore;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersExtraction>;\$<LINK_ONLY:VTK::FiltersSources>"
)

# Create imported target VTK::ImagingSources
add_library(VTK::ImagingSources STATIC IMPORTED)

set_target_properties(VTK::ImagingSources PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::ImagingCore>"
)

# Create imported target VTK::ImagingGeneral
add_library(VTK::ImagingGeneral STATIC IMPORTED)

set_target_properties(VTK::ImagingGeneral PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.1"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtkbuild>;VTK::CommonExecutionModel;VTK::ImagingCore;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::ImagingSources>"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/VTK-targets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
